### PR TITLE
feat: extend matching

### PR DESCRIPTION
**Pull request by ldez**
Related to https://github.com/alingse/asasalint/pull/15#issuecomment-1186157704

### CODE REVIEW

**Comment by alingse** [comment]
i think it's too complex for user to use. if someone want to exclude  simple func name `Wrapf`, they need write  `.*\.Wrapf` .

maybe we can add it when any user report they need this kind of feature.

current, i can say i don't know, there might be not too much user or not too much errors found.

**Comment by ldez** [comment]
It's the same syntax as [forbidigo](https://golangci-lint.run/usage/linters/#forbidigo), I'm don't think this is too complex to use.

**Comment by ldez** [comment]
FYI you can just right `\.Wrapf` because it's a simple match and not a full match.

**Comment by alingse** [comment]
> FYI you can just use `\.Wrapf` because it's a simple match and not a full match.

i try one here https://go.dev/play/p/tGtDtl2eTxb

yes `regexp`  check match is not a full match.

**Pull request merged**
